### ISSUE TITLE
found java.lang.NullPointerException in Gameview

### ISSUE THREAD

**Issue by linuxluigi** [HoboOthello/HoboOthello#4]
It's look like as getJMenuBar() is not init, please fix it Björn :)

Exceptions are in 
this.getJMenuBar().add(gameMenu);
and 
this.getJMenuBar().add(aboutMenu);
Link: [Gameview.java](https://github.com/HoboOthello/HoboOthello/blob/master/src/main/java/de/htw_berlin/HoboOthello/GUI/Gameview.java#L83)

Maybe is this a help: [http://stackoverflow.com](http://stackoverflow.com/questions/15197716/trouble-adding-jmenubar-to-extended-jframe)

**Comment by bjoernuhlig** [comment]
solved!
